site_name: Aix-DB 大模型数据助手
nav:
    - 🏠 配置说明: index.md
    - 📖 源码理解: source-code-guide.md
    - 🚀 部署与开发: deployment-guide.md
    - 🔑 API Token: api-token-guide.md

# 代码仓库信息
repo_name: qinlei131479/Ai-Chat-DB
repo_url: https://github.com/qinlei131479/Ai-Chat-DB


theme:
  name: material
  language: zh
  features:
    - announce.dismiss
    - content.code.copy
    - navigation.top
    - navigation.expand


plugins:
  - tags
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: false
          name: English
          build: true
        - locale: zh
          default: true
          name: 简体中文
          nav_translations:

copyright: Copyright &copy; 2025 Aix-DB
